### ISSUE TITLE
Add a login page for admin

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/UBA#16]
A simple login page for admin to login and view the console. Thus limiting the number of users who can access the dashboard
@ShishirSinha Want to work on it for getting started ?

**Comment by ShishirSinha** [comment]
Yes sir

**Comment by tinaoberoi** [comment]
Hi @kaiiyer , is anybody still working on it ? If not I would like to take this up.

**Comment by Jovonni** [comment]
@tinaoberoi we still need this on http://github.com/TomorrowSoc/OpenUBA so this would be good

**Comment by kaiiyer** [comment]
@tinaoberoi Yeah you can take up the issue and work on it !!

**Comment by Swapnil074** [comment]
Hey @kaiiyer i want to work on it
