### ISSUE TITLE
Add a sample D3 Force Directed Graph

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/UBA#21]
Refer https://observablehq.com/@d3/force-directed-graph & https://github.com/d3/d3-force !!

Add a force directed graph to illustrate network traffic

**Comment by Jovonni** [comment]
We will be using graphx, and network x to do our graphs on the backend, this is good ur using d3 to display it on the front end. Good idea

**Comment by agnes-sharan** [comment]
Hi I'd like to take up this issue for GSSoC

**Comment by kaiiyer** [comment]
Okay go ahead !
