### ISSUE TITLE
Add a continuous integration service

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/UBA#23]
Adding a continuous integration service like TravisCI or CircleCI can help automate the software builds, tests, and deploymentsAdding a continuous integration service like TravisCI or CircleCI can help automate the software builds, tests, and deployments

**Comment by tinaoberoi** [comment]
I would like to work on this. Is it okay, if I take this up ?

**Comment by kaiiyer** [comment]
Yeah sure. I've assigned the issue to you !!
I've already added Travis CI so you can work on CircleCI or any other CI service
